### PR TITLE
Use message box to fix #12 that was not solve in ctimer_db branch

### LINKED ISSUE #12: [Feature Request] Hints before and after clock
## Is your feature request related to a problem?
It is good to have an overview of what you are going to do in the coming 25 minutes and after the clock has finished. 
## Describe the solution you'd like
A prompt for users to answer their goals (before clock) + a prompt for users to answer what they achieved and what can be improved (after clock) 
 
## Invite the community to discuss and vote
Earn votes and support by involving the community and invite everybody to discuss your feature and
to vote for it (votes are +1 , 0 or -1 via adding a **thumbs-up/down**)

### PR DESCRIPTION
**Pull request by zztin**
(Thanks for sending a pull request! Please fill in the following content to let us know better about this change.)

## Types of changes
Please put an `x` in the box that applies

- [x] **Bugfix**
- [x] **New feature**
- [ ] **Refactoring**
- [ ] **Breaking change** (any change that would cause existing functionality to not work as expected)
- [ ] **Documentation Update**
- [ ] **Other (please describe)**

## Description
The messages after a clock finishes are now prompt with tikinter default messagebox and simpledialog, solving the problem previously which the main window keep going while not waiting for response from subwindows.

## Steps to Test This Pull Request
1. in concentrationtimer.py: Disable line 30 and enable line 29 temporary for quickly checking results.
2. launch ctimer in terminal (make sure it was installed with developer mode)
3. Start the clock and enters a goal
4. finish the clock
5. Answers the prompt windows by clicking "no"
6. Enter a reason in the next window.
7. Repeat 2-4 and answer yes in the second clock.
8. terminate ctimer app.
9. Check stored database at path: ctimer/data/ctimer.db --> drag and drop in https://inloop.github.io/sqlite-viewer/
10. if the entries you typed are stored correctly, accept the pull request.

## Expected behavior
1. Database is updated as user input.
2. No errors in command line.

## Related Issue
#12 #6

### CODE REVIEW

**Comment by tai271828** [comment]
Right after complete step#6 I got

```
unable to open database file
Welcome                                                      
2020-07-09 21:56:14.019 GSSpeechServer[10597:10597] No handle for event rport on descriptor 13
2020-07-09 21:56:17.412 GSSpeechServer[10597:10597] No handle for event rport on descriptor 13
2020-07-09 21:56:49.704 GSSpeechServer[10597:10597] No handle for event rport on descriptor 13
unable to open database file                                    
Exception in Tkinter callback                                  
Traceback (most recent call last):                                                                                    
  File "/home/tai271828/.pyenv/versions/3.8.3/lib/python3.8/tkinter/__init__.py", line 1883, in __call__                
    return self.func(*args)                                            
  File "/home/tai271828/.pyenv/versions/3.8.3/lib/python3.8/tkinter/__init__.py", line 804, in callit
    func(*args)
  File "/home/tai271828/work-my-projects/ctimer/ctimer/concentratetimer/concentratetimer.py", line 117, in countdown
    db.db_add_clock_details(self.db_file, self.clock_details)                                 
  File "/home/tai271828/work-my-projects/ctimer/ctimer/concentratetimer/ctimer_db.py", line 24, in db_add_clock_details
    with conn:                                                                                
AttributeError: __enter__
```

By manually creating a folder `data` under the project root, we could workaround this issue.

**Comment by zztin** [comment]
Data path Issue fixed. Ready for pull review.

**Comment by tai271828** [comment]
Hi, you pushed your db binary to the repository.

**Comment by tai271828** [comment]
Testing looks good. Thanks for the effort!

**Pull request merged**
